version: '3.8'
services:
  app:
    build: .
    image: awsjirabotgui
    ports:
      - "8080:8080"
    environment:
      - .env
    # For AWS credentials, it's best to mount the host's AWS config
    # volumes:
    #   - ~/.aws:/root/.aws:ro